### ISSUE TITLE
wrong UDP port and VNI values

### ISSUE THREAD

**Issue by alxmats** [PaloAltoNetworks/Azure-GWLB#2]
## Documentation link
https://github.com/PaloAltoNetworks/Azure-GWLB/blob/main/Beta/README.md

## The problem
Inaccuracy. Wrong UDP port numbers and VNI id in init-cfg.txt. JSON-template for GWLB define different values.

## Suggested fix
`plugin-op-commands=azure-gwlb-inspect:enable+internal-port-2000+external-port-2001+internal-vni-900,external-vni-901`

**Comment by alxmats** [comment]
Add to README useful command 
`show plugins vm_series azure gwlb`
It could help while deploying GWLB.

**Comment by skrish-murt** [comment]
Fixed. Detailed description has been given in the [README.md](https://github.com/PaloAltoNetworks/Azure-GWLB/blob/main/README.md)
