### ISSUE TITLE
bootstrap.xml

### ISSUE THREAD

**Issue by sijusamueltech** [PaloAltoNetworks/Azure-GWLB#3]
## Describe the bug
In the bootstrap folder did not see a bootstrap.xml. How do we get the required the configurations with in Palo Alto?

When deployed in Azure, the NVA spun up did not have any   configurations specific to the over all network layout (interfaces, zones etc).   Providing a corresponding bootstrap.xml file would be helpful 

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by cgtheflash** [comment]
Had to manually enable gwlb with 'request plugins vm_series azure gwlb inspect enable yes'. Couldn't get bootstrap init-config.txt to take for some reason. 

Still cannot get this solution to work at all though. Palo's fully configured and healthy in the load balancer but not seeing traffic for the application.

Readme is missing Palo configuration as well.

**Comment by skrish-murt** [comment]
`bootstrap.xml` has been added in the latest commit. You can find it in the [bootstrap.tgz](https://github.com/PaloAltoNetworks/Azure-GWLB/blob/main/bootstrap.tgz) folder.
